# Generated by docs/rcx/gen_study.py -- do not edit by hand.
export PLATFORM               = ihp-sg13g2
export DESIGN_NAME            = fanout_8
export DESIGN_NICKNAME        = rcx-fanout-8

export VERILOG_FILES          = $(DESIGN_HOME)/src/rcx-fanout/fanout_8.v
export SDC_FILE               = $(DESIGN_HOME)/ihp-sg13g2/rcx-fanout-8/constraint.sdc
export IO_CONSTRAINTS         = $(DESIGN_HOME)/ihp-sg13g2/rcx-fanout-8/io.tcl

export DIE_AREA               = 0 0 500.0 160.0
export CORE_AREA              = 26.0 26.0 474.0 134.0
export PLACE_DENSITY          = 0.10

# Tiny design: keep the run fast.
export SKIP_LAST_GASP         ?= 1
