# hardcoded list of paths to exclude while we incrementally lint codebase
# See issue #3268 for tracking
exclude = [
    "flow/results",
    "flow/logs",
    "flow/designs/asap7/cva6/constraint.sdc",
    "tools/OpenROAD",
    "tools/yosys",
    "tools/yosys-slang",
]

ignore = [
    "unbraced-expr",
]

[style]
indent = 2
line-length = 100
indent-namespace-eval = false
spaces-in-braces = true