# Generated by docs/rcx/gen_study.py -- do not edit by hand.
export PLATFORM               = sky130hd
export DESIGN_NAME            = fanout_128
export DESIGN_NICKNAME        = rcx-fanout-128

export VERILOG_FILES          = $(DESIGN_HOME)/src/rcx-fanout/fanout_128.v
export SDC_FILE               = $(DESIGN_HOME)/sky130hd/rcx-fanout-128/constraint.sdc
export IO_CONSTRAINTS         = $(DESIGN_HOME)/sky130hd/rcx-fanout-128/io.tcl

export DIE_AREA               = 0 0 776.0 198.0
export CORE_AREA              = 12.0 12.0 764.0 186.0
export PLACE_DENSITY          = 0.10

# Tiny design: keep the run fast.
export SKIP_LAST_GASP         ?= 1
