load("//flow/designs:design.bzl", "design")

design(
    config = "config.mk",
    user_arguments = [
        "IO_EAST_PINS",
        "IO_NORTH_PINS",
        "IO_SOUTH_PINS",
        "IO_WEST_PINS",
    ],
    user_sources = [
        "ADDITIONAL_FAST_LIBS",
        "ADDITIONAL_SLOW_LIBS",
    ],
)
