utl::set_metrics_stage "floorplan__{}"
source $::env(SCRIPTS_DIR)/load.tcl
erase_non_stage_variables synth
load_design 1_2_yosys.v 1_2_yosys.sdc
source_step_tcl PRE SYNTH

# Eliminate dead logic before writing the synthesis odb so that
# 1_synth.odb already reflects the live design.
#
# This matters for parallel synthesis flows (e.g., MegaBoom) where yosys
# only sees a slice of the design at a time and cannot prune logic that
# is dead only when looking at the whole design. In those flows this
# step can eliminate vast quantities of debug logic — for MegaBoom it
# has historically removed ~50% of the design.
#
# eliminate_dead_logic is a pure netlist transform: it does not need a
# die area, bterm placement or routing layers, so it is safe to run
# here. Other synthesis-looking transforms in floorplan.tcl
# (repair_tie_fanout, replace_arith_modules, remove_buffers,
# repair_timing_helper) DO depend on floorplan-stage context (bterm
# locations from initialize_floorplan, routing-layer setup) and must
# stay in floorplan.tcl — moving them here was tried in PR #4187 and
# regressed setup TNS by 1.7-46x on I/O-heavy designs (asap7/aes-block,
# asap7/jpeg_lvt, asap7/swerv_wrapper, nangate45/ariane133).
log_cmd eliminate_dead_logic

source_step_tcl POST SYNTH
orfs_write_db $::env(RESULTS_DIR)/1_synth.odb
# Canonicalize 1_synth.sdc. The original SDC_FILE provided by
# the user could have dependencies, such as sourcing util.tcl,
# which are read in here and a canonicalized version is written
# out by OpenSTA that has no dependencies.
orfs_write_sdc $::env(RESULTS_DIR)/1_synth.sdc

# Emit port-only stub LEF + Liberty for the synthesized design so a
# parent that instantiates this design as a macro can complete its
# synth_odb stage without waiting on our floorplan/place/cts to
# produce real LEF and post-place Liberty. The stub LEF carries only
# port names + directions (no geometry); the Liberty is generated by
# OpenSTA's write_timing_model and carries arc delays computed from
# the loaded netlist with ideal clocks. Together they are enough to
# satisfy read_lef + read_liberty + read_verilog + dbInst::create at
# the parent's synth_odb, and enough for the parent's synth-time STA
# to compute path delays through macro arcs.
if { [info exists ::env(ORFS_WRITE_SYNTH_STUBS)] && $::env(ORFS_WRITE_SYNTH_STUBS) == "1" } {
  set design $::env(DESIGN_NAME)
  set block [ord::get_db_block]

  # Per-design filename so OpenROAD's lefin doesn't reject the second
  # stub LEF in a parent's synth_odb with `ODB-0229 Error: library
  # (1_synth) already exists` — lefin derives the library name from
  # the LEF file's basename, and a parent reading multiple sibling
  # stubs would otherwise see colliding "1_synth" libraries.
  set lef_file $::env(RESULTS_DIR)/${design}_1_synth.lef
  set f [open $lef_file w]
  puts $f "VERSION 5.7 ;"
  puts $f "BUSBITCHARS \"\[\]\" ;"
  puts $f "DIVIDERCHAR \"/\" ;"
  puts $f ""
  puts $f "MACRO $design"
  puts $f "  CLASS BLOCK ;"
  puts $f "  ORIGIN 0 0 ;"
  puts $f "  SIZE 1 BY 1 ;"
  puts $f "  SYMMETRY X Y ;"
  foreach bterm [$block getBTerms] {
    set pname [$bterm getName]
    set io [$bterm getIoType]
    if { $io eq "FEEDTHRU" } {
      continue
    }
    puts $f "  PIN $pname"
    puts $f "    DIRECTION $io ;"
    puts $f "    USE SIGNAL ;"
    puts $f "  END $pname"
  }
  puts $f "END $design"
  puts $f ""
  puts $f "END LIBRARY"
  close $f

  # Emit a real-timing Liberty via OpenSTA's write_timing_model with
  # ideal clocks. The synthesized netlist is already loaded; PDK
  # Liberty is loaded too. write_timing_model characterises the
  # design as a Liberty cell with arc delays derived from the
  # current STA setup. Without parasitics, the arcs are optimistic
  # compared to post-place .lib but include cell delays through
  # the macro — enough to keep a parent's synth-stage WNS within
  # noise of the legacy (post-place-lib) flow.
  set lib_file $::env(RESULTS_DIR)/${design}_1_synth.lib
  set_clock_latency -source 0 [all_clocks]
  if { [env_var_exists_and_non_empty CORNERS] } {
    log_cmd write_timing_model -scene [lindex $::env(CORNERS) 0] $lib_file
  } else {
    log_cmd write_timing_model $lib_file
  }
}
