# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-test-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: gcr.io/foss-fpga-tools-ext-openroad/ray
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "echo <CMD>"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
