// Generated by docs/rcx/gen_study.py -- do not edit by hand.
//
// Left-to-right fan-out macro: a single launch flop ("hub") drives a net that
// fans out to 8 capture flop(s). Inputs are on the WEST edge, outputs on the
// EAST edge (see io.tcl), so the fan-out net spans the die. Each sink is XOR'd
// with its own perturb bit and bonded to a distinct output, so synthesis can
// neither merge nor delete sinks. The hub is dont_touch so the resizer cannot
// clone the driver and shorten the net (which would erase the effect we study).
module fanout_8 (
    input  wire           clock,
    input  wire           reset,
    input  wire           din,
    input  wire [7:0] perturb,
    output reg  [7:0] dout
);
    (* dont_touch = "true" *) reg hub;
    always @(posedge clock) begin
        if (reset) hub <= 1'b0;
        else       hub <= din;
    end

    integer i;
    always @(posedge clock) begin
        if (reset) dout <= {8{1'b0}};
        else begin
            for (i = 0; i < 8; i = i + 1)
                dout[i] <= hub ^ perturb[i];
        end
    end
endmodule
