blank_issues_enabled: false
contact_links:
  - name: OpenROAD Flow Scripts Discussions
    url: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/discussions 
    about: Please ask and answer questions here.