export DESIGN_NICKNAME = jpeg
export DESIGN_NAME = jpeg_encoder
export PLATFORM    = sky130hd

export VERILOG_FILES = $(sort $(wildcard $(DESIGN_HOME)/src/$(DESIGN_NICKNAME)/*.v))
export VERILOG_INCLUDE_DIRS = $(DESIGN_HOME)/src/$(DESIGN_NICKNAME)/include
export SDC_FILE      = $(DESIGN_HOME)/$(PLATFORM)/$(DESIGN_NICKNAME)/constraint.sdc

#export CORE_UTILIZATION = 50
#export PLACE_DENSITY_LB_ADDON = 0.15
export TNS_END_PERCENT = 100

export FASTROUTE_TCL = $(DESIGN_HOME)/$(PLATFORM)/$(DESIGN_NICKNAME)/fastroute.tcl

export REMOVE_ABC_BUFFERS = 1

# AutoTuner mods to trigger checkConnectivity issue
export CELL_PAD_IN_SITES_DETAIL_PLACEMENT = 0
export CELL_PAD_IN_SITES_GLOBAL_PLACEMENT = 2
export CORE_ASPECT_RATIO = 1.1758835998750026
export CORE_MARGIN = 2
export CORE_UTILIZATION = 41
export CTS_CLUSTER_DIAMETER = 185
export CTS_CLUSTER_SIZE = 163
export PLACE_DENSITY_LB_ADDON = 0.045165825696229456

#export _FR_GR_OVERFLOW = 1
export PLACE_PINS_ARGS = -min_distance 1
