# Target with dependencies to run all flow tools from their pre-compiled
# binaries.
FROM openroad/centos7-runtime
RUN yum update -y \
    && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum group install -y "Development Tools" \
    && yum install -y https://www.klayout.org/downloads/CentOS_7/klayout-0.27.1-0.x86_64.rpm \
    && yum install -y tcl tcl-tclreadline-devel tcllib time \
    && pip3 install pandas
