# create image with dependencies needed to compile openroad app and run openroad flow scripts
# NOTE: don't use this file directly unless you know what you are doing,
# instead use etc/DockerHelper.sh
ARG fromImage=centos:centos7

FROM $fromImage

WORKDIR /tmp/installer/etc

COPY DependencyInstaller.sh .
COPY requirements.txt .

COPY InstallerOpenROAD.sh \
       /tmp/installer/tools/OpenROAD/etc/DependencyInstaller.sh

RUN ./DependencyInstaller.sh \
      && rm -rf /tmp/installer

ARG fromImage

RUN echo "$fromImage" | grep -q "ubuntu" && \
    strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so || \
    echo "Skipping strip command as fromImage does not contain 'ubuntu'"
