# create image with dependencies needed to compile openroad app and run openroad flow scripts
# NOTE: don't use this file directly unless you know what you are doing,
# instead use etc/DockerHelper.sh
ARG fromImage=ubuntu:22.04

FROM $fromImage

WORKDIR /tmp/installer/etc

COPY DependencyInstaller.sh .

COPY InstallerOpenROAD.sh \
       /tmp/installer/tools/OpenROAD/etc/DependencyInstaller.sh

ARG options=""
ARG constantBuildDir="-constant-build-dir"

RUN env CFLAGS="-D__TIME__=0 -D__DATE__=0 -D__TIMESTAMP__=0 -Wno-builtin-macro-redefined" \
      CXXFLAGS="-D__TIME__=0 -D__DATE__=0 -D__TIMESTAMP__=0 -Wno-builtin-macro-redefined" \
      ./DependencyInstaller.sh $options $constantBuildDir \
      && rm -rf /tmp/installer /tmp/* /var/tmp/* /var/lib/apt/lists/*

ARG fromImage

RUN echo "$fromImage" | grep -q "ubuntu" && \
    strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so || \
    echo "Skipping strip command as fromImage does not contain 'ubuntu'"
