# Generated by docs/rcx/gen_study.py -- do not edit by hand.
export PLATFORM               = asap7
export DESIGN_NAME            = fanout_128
export DESIGN_NICKNAME        = rcx-fanout-128

export VERILOG_FILES          = $(DESIGN_HOME)/src/rcx-fanout/fanout_128.v
export SDC_FILE               = $(DESIGN_HOME)/asap7/rcx-fanout-128/constraint.sdc
export IO_CONSTRAINTS         = $(DESIGN_HOME)/asap7/rcx-fanout-128/io.tcl

export DIE_AREA               = 0 0 264.0 19.8
export CORE_AREA              = 1.0 1.0 263.0 18.8
export PLACE_DENSITY          = 0.10

# Tiny design: keep the run fast.
export SKIP_LAST_GASP         ?= 1
