# Copyright (c) 2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:22.04

COPY ./tools/codespace/scripts/install-orfs.sh /usr/local/bin/install-orfs.sh
RUN bash /usr/local/bin/install-orfs.sh

ENV PATH="$PATH:/usr/local/bin"

ENV PATH="$PATH:/yosys/"
ENV OPENROAD_EXE=/usr/bin/openroad
ENV YOSYS_CMD=/yosys/yosys
