load("//flow/designs:design.bzl", "design")

design(
    config = "config.mk",
    local_arguments = [
        "BC_ADDITIONAL_LIB_FILES",
        "TC_ADDITIONAL_LIB_FILES",
        "WC_ADDITIONAL_LIB_FILES",
    ],
    user_arguments = ["DESIGN_TYPE"],
)
