#!/usr/bin/env python3
"""The E12 gate: does a clustered global placement rank as well as a flat one?

Background. Macro placement candidates are generated by seeding RTL-MP
(`rtl_macro_placer -random_seed`) and then *scored*, because the placer's
own annealing cost predicts area rather than period. The established
scorer is a fast non-timing-driven global placement over every standard
cell -- the "flat" rung. On the archived asap7 swerv_wrapper population
of 24 candidates it ranks the ground truth (the macro-path timing
aggregate measured at global route, after the entire production tail) at
Spearman rho +0.72 with a bootstrap interval of [0.48, 0.84].

E12 asks whether that placement can be run on RTL-MP's own std-cell
clusters instead -- roughly an order of magnitude fewer movables -- and
still rank. This script decides it, on one pre-registered criterion:

    rho(clustered score vs grt macro_paths_mean) must land inside the
    flat scorer's interval, [0.48, 0.84].

A failing verdict is a result, not a defect: it prices the reduction.
Because the truth includes repair_design/repair_timing/CTS/route,
rho(clustered) - rho(flat) *is* the measured cost of the abstraction,
repair-blindness and all.

Two gates, in order. Gate 0 checks the rig: the candidates are
regenerated here, so the regenerated flat scores must reproduce the
archived ones before any clustered number means anything. Gate 1 is the
criterion above. Gate 0 failing means the rig is being measured, not E12.

Inputs:
  --truth         score_vs_flow_swerv.json -- the committed archive:
                  per candidate, `grt` (ground truth) and `proxy` (the
                  flat score that was measured alongside it)
  --evidence-dir  the run's leaves: cand_s<N>.json (flat, from
                  macro_e12.tcl) and cand_s<N>.clustered.json (from
                  score_clustered.tcl)
  --out           verdict JSON
"""

import argparse
import json
import os
import sys

from e12_stats import spearman, spearman_ci

# The flat scorer's measured interval on the macro-path KPI. Not a
# tunable: it is the published reference this experiment is graded
# against, and moving it would move the goalposts.
#
# Specifically this is the interval of REFERENCE_VARIANT below, i.e.
# rho(flat proxy's general-path aggregate, grt macro_paths_mean) =
# +0.72 [0.48, 0.84]. Recomputing it from the committed archive is a
# unit test, not an act of faith. Note that the flat proxy's *macro*-path
# aggregate ranks the same truth better still, +0.82 [0.61, 0.92]; the
# conservative scalar is used as the reference on purpose, because the
# clustered rung's score is a wirelength scalar rather than an STA
# aggregate and the published HPWL-only floor (+0.67) sits inside this
# interval.
FLAT_CI = (0.48, 0.84)

REFERENCE_VARIANT = "archive_flat_wq25"

# Ground-truth KPIs, from the archive's `grt` block. The gate rides on
# macro_paths_mean; the rest are reported because a scorer that ranks the
# wrong KPI well is worth knowing about.
TRUTH_KPIS = ("macro_paths_mean", "achieved", "general_paths_mean", "stdcell_um2")

GATE_KPI = "macro_paths_mean"

CLUSTERED_SUFFIX = ".clustered.json"

# Score variants. Each is (label, source, field), where source picks the
# per-candidate record to read the field out of. Every variant is
# oriented so that *lower is better*, which is why they are all expected
# to correlate positively with the period KPIs.
VARIANTS = (
    ("archive_flat_wq25", "archive_proxy", "wq25"),
    ("archive_flat_macro_mean", "archive_proxy", "macro_mean"),
    ("archive_objective", "archive_objective", "objective_fixed_norm"),
    ("regen_flat_wq25", "flat", "wq25"),
    ("regen_flat_macro_mean", "flat", "macro_mean"),
    ("regen_flat_hpwl", "flat", "hpwl_dbu"),
    ("clustered_hpwl", "clustered", "hpwl_dbu"),
    ("clustered_cone_hpwl", "clustered", "cone_hpwl_dbu"),
)

# Fields whose regeneration gate 0 checks per candidate. Both are STA
# aggregates the flat rung reports, so both must come back identical if
# `-random_seed` really made the candidate reproducible.
REPRODUCED_FIELDS = ("wq25", "macro_mean")

# Cost fields worth carrying next to the ranking, so the
# accuracy-vs-cost curve can be drawn from the evidence rather than
# estimated. The counts are what make the claimed reduction checkable.
COST_FIELDS = (
    "gpl_s",
    "clusters_declared",
    "clustered_insts",
    "halo_flat_insts",
    "signal_nets",
    "cone_nets",
    "vmhwm_kb",
)


def load_json(path):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def load_leaves(evidence_dir, suffix, exclude=()):
    """Per-candidate leaves, keyed by tag.

    `exclude` keeps the flat leaves (cand_s0.json) from also matching the
    clustered ones (cand_s0.clustered.json), which share the .json tail.
    """
    leaves = {}
    if not os.path.isdir(evidence_dir):
        return leaves
    for name in sorted(os.listdir(evidence_dir)):
        if not name.endswith(suffix):
            continue
        if any(name.endswith(other) for other in exclude):
            continue
        tag = name[: -len(suffix)]
        leaves[tag] = load_json(os.path.join(evidence_dir, name))
    return leaves


def collect(truth, flat, clustered):
    """Per-tag records, one dict per source, over the common tags only."""
    archive = truth["candidates"]
    tags = sorted(set(archive) & set(flat) & set(clustered)) if clustered else []
    if not tags:
        # Gate 0 can be evaluated before any clustered leaf exists.
        tags = sorted(set(archive) & set(flat))
    return tags, {
        "grt": {t: archive[t]["grt"] for t in tags},
        "archive_proxy": {t: archive[t]["proxy"] for t in tags},
        "archive_objective": {
            t: {"objective_fixed_norm": archive[t]["objective_fixed_norm"]}
            for t in tags
            if "objective_fixed_norm" in archive[t]
        },
        "flat": {t: flat[t] for t in tags if t in flat},
        "clustered": {t: clustered[t] for t in tags if t in clustered},
    }


def rho_table(tags, sources, n_boot):
    """rho and CI for every (variant, truth KPI) pair that has data."""
    table = {}
    for label, source, field in VARIANTS:
        records = sources.get(source, {})
        usable = [t for t in tags if t in records and field in records[t]]
        if len(usable) < 3:
            continue
        scores = [records[t][field] for t in usable]
        per_kpi = {}
        for kpi in TRUTH_KPIS:
            truth_vals = [sources["grt"][t][kpi] for t in usable]
            rho = spearman(scores, truth_vals)
            low, high = spearman_ci(scores, truth_vals, n_boot=n_boot)
            per_kpi[kpi] = {"rho": rho, "ci": [low, high]}
        table[label] = {"n": len(usable), "kpi": per_kpi}
    return table


def cost_table(tags, sources):
    """Mean of each cost field, per source, over the candidates that have it."""
    costs = {}
    for source in ("flat", "clustered"):
        records = sources.get(source, {})
        per_field = {}
        for field in COST_FIELDS:
            values = [
                records[t][field] for t in tags if t in records and field in records[t]
            ]
            if values:
                per_field[field] = sum(values) / len(values)
        if per_field:
            costs[source] = per_field
    return costs


def gate_zero(tags, sources, tolerance):
    """Did the regenerated flat scores reproduce the archived ones?

    Reproduction is checked on ranking (rho against the same truth) and,
    more strictly, per candidate: the point of `-random_seed` is that a
    candidate is reproducible, so a mismatch means the rig drifted --
    a different OpenROAD, a different floorplan, a lost patch -- and
    every downstream number would be measuring that instead of E12.
    """
    flat = sources.get("flat", {})
    archive = sources.get("archive_proxy", {})
    usable = [t for t in tags if t in flat and t in archive]
    mismatches = []
    for tag in usable:
        for field in REPRODUCED_FIELDS:
            want = archive[tag].get(field)
            got = flat[tag].get(field)
            if want is None or got is None:
                mismatches.append(
                    {"tag": tag, "field": field, "reason": "value missing"}
                )
                continue
            if want == 0:
                continue
            relative = abs(got - want) / abs(want)
            if relative > tolerance:
                mismatches.append(
                    {
                        "tag": tag,
                        "field": field,
                        "archived": want,
                        "regenerated": got,
                        "relative_error": relative,
                    }
                )
    return {
        "candidates_compared": len(usable),
        "fields_compared": list(REPRODUCED_FIELDS),
        "relative_tolerance": tolerance,
        "mismatches": mismatches,
        "pass": bool(usable) and not mismatches,
    }


def gate_one(table, expected_n):
    """The E12 criterion itself."""
    entry = table.get("clustered_hpwl")
    if entry is None:
        return {
            "pass": False,
            "reason": "no clustered scores present",
        }
    stats = entry["kpi"][GATE_KPI]
    rho = stats["rho"]
    inside = FLAT_CI[0] <= rho <= FLAT_CI[1]
    complete = entry["n"] == expected_n
    return {
        "kpi": GATE_KPI,
        "rho": rho,
        "ci": stats["ci"],
        "flat_ci": list(FLAT_CI),
        "n": entry["n"],
        "expected_n": expected_n,
        "inside_flat_ci": inside,
        "population_complete": complete,
        "pass": bool(inside and complete),
    }


def diverged_tags(sources):
    return sorted(
        tag
        for tag, record in sources.get("clustered", {}).items()
        if record.get("diverged")
    )


def format_report(verdict):
    lines = []
    gate0 = verdict["gate_0_rig_check"]
    lines.append(
        "Gate 0 (rig check): {} -- {} candidates compared, {} mismatches".format(
            "PASS" if gate0["pass"] else "FAIL",
            gate0["candidates_compared"],
            len(gate0["mismatches"]),
        )
    )
    for bad in gate0["mismatches"][:5]:
        lines.append("    {}".format(bad))

    lines.append("")
    lines.append("rho vs ground truth (n, then per KPI):")
    header = "  {:<26} {:>3}".format("variant", "n")
    for kpi in TRUTH_KPIS:
        header += "  {:>26}".format(kpi)
    lines.append(header)
    for label, entry in verdict["rho"].items():
        row = "  {:<26} {:>3}".format(label, entry["n"])
        for kpi in TRUTH_KPIS:
            stats = entry["kpi"][kpi]
            row += "  {:>+8.2f} [{:>+6.2f},{:>+6.2f}]".format(
                stats["rho"], stats["ci"][0], stats["ci"][1]
            )
        lines.append(row)

    if verdict["cost"]:
        lines.append("")
        lines.append("mean cost per candidate:")
        for source, fields in verdict["cost"].items():
            lines.append("  {}:".format(source))
            for field, value in fields.items():
                lines.append("    {:<20} {:.2f}".format(field, value))

    if verdict["diverged"]:
        lines.append("")
        lines.append("DIVERGED (not scorable): {}".format(verdict["diverged"]))

    gate1 = verdict["gate_1_e12"]
    lines.append("")
    if "reason" in gate1:
        lines.append("Gate 1 (E12): FAIL -- {}".format(gate1["reason"]))
    else:
        lines.append(
            "Gate 1 (E12): {} -- rho(clustered_hpwl vs {}) = "
            "{:+.2f} [{:+.2f}, {:+.2f}], flat interval "
            "[{:+.2f}, {:+.2f}], n = {}/{}".format(
                "PASS" if gate1["pass"] else "FAIL",
                gate1["kpi"],
                gate1["rho"],
                gate1["ci"][0],
                gate1["ci"][1],
                gate1["flat_ci"][0],
                gate1["flat_ci"][1],
                gate1["n"],
                gate1["expected_n"],
            )
        )
    return "\n".join(lines)


def build_verdict(truth, flat, clustered, expected_n, n_boot, tolerance):
    tags, sources = collect(truth, flat, clustered)
    table = rho_table(tags, sources, n_boot)
    return {
        "design": truth.get("design"),
        "population": truth.get("population"),
        "tags": tags,
        "rho": table,
        "cost": cost_table(tags, sources),
        "diverged": diverged_tags(sources),
        "gate_0_rig_check": gate_zero(tags, sources, tolerance),
        "gate_1_e12": gate_one(table, expected_n),
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--truth",
        required=True,
        help="score_vs_flow_swerv.json, the committed archive",
    )
    parser.add_argument(
        "--evidence-dir",
        required=True,
        help="directory holding cand_s*.json and cand_s*.clustered.json",
    )
    parser.add_argument("--out", help="write the verdict JSON here")
    parser.add_argument(
        "--expected-n",
        type=int,
        default=24,
        help="candidates the gate requires (default: the archived 24)",
    )
    parser.add_argument("--n-boot", type=int, default=4000)
    parser.add_argument(
        "--tolerance",
        type=float,
        default=1e-6,
        help="relative tolerance for gate 0 reproduction",
    )
    parser.add_argument(
        "--allow-fail",
        action="store_true",
        help="report the verdict but exit 0 even if a gate fails",
    )
    args = parser.parse_args(argv)

    verdict = build_verdict(
        load_json(args.truth),
        load_leaves(args.evidence_dir, ".json", exclude=(CLUSTERED_SUFFIX,)),
        load_leaves(args.evidence_dir, CLUSTERED_SUFFIX),
        args.expected_n,
        args.n_boot,
        args.tolerance,
    )
    print(format_report(verdict))
    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            json.dump(verdict, handle, indent=1, sort_keys=True)
            handle.write("\n")

    passed = verdict["gate_0_rig_check"]["pass"] and verdict["gate_1_e12"]["pass"]
    return 0 if (passed or args.allow_fail) else 1


if __name__ == "__main__":
    sys.exit(main())
