#!/usr/bin/env python3

# Script for generating and comparing per-layer parasitics values.
# These values are used by set_layer_rc and will be the base
# values for the parasitics estimations across the flow.

import os
from sys import exit, stderr
from collections import defaultdict

import traceback
import collections
import argparse
import re
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

LAYER_HEADER_RE = re.compile("^([^\\(]+)\\(([^\\)]+)\\)$")

# Helper functions
# =============================================================================


# sklearn's default baseline model for scoring the fit i.e., measuring R² is
# "predict the mean" which is not the proper model for our regressions since
# both R and C are through-origin fits - the R² computation doesn't behave
# well for var(y) ≈ 0 - so we compute R² manually with a "predict zero"
# baseline model.
def compute_through_origin_fit_score(model, inputs, observed):
    sum_squared_observed = (observed**2).sum()
    if sum_squared_observed == 0:
        return "No data"
    score = 1.0 - ((observed - model.predict(inputs)) ** 2).sum() / sum_squared_observed
    return f"{score:.4f}"


# Parse and validate arguments
# =============================================================================


def parse_args():
    parser = argparse.ArgumentParser(
        description="Determines layer capacitance and resistance values for OpenROAD flow designs"
    )
    parser.add_argument(
        "-cap_unit", required=False, default="pf", help="capacitance unit ff|pf"
    )
    parser.add_argument(
        "-res_unit", required=False, default="kohm", help="resistance unit ohm|kohm"
    )
    parser.add_argument(
        "-plot_cap",
        required=False,
        action="store_true",
        default=False,
        help="Plot grt/rcx capacitance differences",
    )
    parser.add_argument(
        "-plot_res",
        required=False,
        action="store_true",
        default=False,
        help="Plot grt/rcx resistance differences",
    )
    parser.add_argument(
        "--mode",
        required=False,
        choices=["net", "segment"],
        default="net",
        help="Input mode: 'net' for net-level RC (make write_net_rc), 'segment' for segment-level RC (make write_segment_rc)",
    )
    parser.add_argument(
        "rc_file", nargs="+", help="rc csv file written by make compare_rc"
    )
    args = parser.parse_args()

    return args


args = parse_args()

# kohm/ff nangate45, asap7
# kohm/pf sky130hd, sky130hs

res_unit = args.res_unit
if res_unit == "ohm":
    res_scale = 1
elif res_unit == "kohm":
    res_scale = 1e3
else:
    print("unknown resistance unit")
    exit(1)

cap_unit = args.cap_unit
if cap_unit == "ff":
    cap_scale = 1e-15
elif cap_unit == "pf":
    cap_scale = 1e-12
else:
    print("unknown capacitance unit")
    exit(1)


def makeDict():
    return collections.defaultdict(makeDict)


data = makeDict()

stack = []
stack_line = None

# For segment mode.
layer_segments = defaultdict(
    lambda: {"lengths": [], "resistances": [], "capacitances": []}
)
layer_net_type_length = defaultdict(lambda: defaultdict(float))
routing_layers = []
routing_layers_line = None

# indices of relevant layers (routable layers or via layers)
active_layers = set()

# Parse the cap CSV file generated by compare_rc_script.tcl
for rc_file in args.rc_file:
    design = rc_file
    print("reading", design)
    with open(rc_file) as f:
        nonGrtNets = 0
        for line in f:
            if line.startswith("# routing layers: "):
                if routing_layers_line is not None and routing_layers_line != line:
                    print(f"layer stack inconsistent", file=stderr)
                    exit(1)
                elif routing_layers_line is None:
                    routing_layers = (
                        line.removeprefix("# routing layers: ").strip().split(" ")
                    )
                    routing_layers_line = line
                continue

            if line.startswith("# stack: "):
                if stack_line is not None and stack_line != line:
                    print(f"layer stack inconsistent", file=stderr)
                    exit(1)
                elif stack_line is None:
                    for layer in line.removeprefix("# stack: ").strip().split(" "):
                        name = layer
                        is_routing = False
                        via_resist = 0.0
                        if layer.endswith(")"):
                            # layer name has extra data
                            match = LAYER_HEADER_RE.match(layer)
                            assert match
                            name = match.group(1)
                            if match.group(2) == "routing":
                                is_routing = True
                            else:
                                via_resist = float(match.group(2))
                        stack.append((name, is_routing, via_resist))
                    stack_line = line
                continue

            if line.startswith("#"):
                continue

            tokens = line.strip().split(",")

            if args.mode == "segment":
                layer_segments[tokens[2]]["lengths"].append(float(tokens[3]))
                layer_segments[tokens[2]]["resistances"].append(float(tokens[4]))
                layer_segments[tokens[2]]["capacitances"].append(float(tokens[5]))
                layer_net_type_length[tokens[2]][tokens[1]] += float(tokens[3])
            else:
                netName = tokens[0]

                # net CSV: name,type,fanout,grt_res,grt_cap,rcx_res,rcx_cap,<per-layer length>
                data[design][netName] = {
                    "type": tokens[1],
                    "fanout": int(tokens[2]),
                    "grt_res": float(tokens[3]),
                    "grt_cap": float(tokens[4]),
                    "rcx_res": float(tokens[5]),
                    "rcx_cap": float(tokens[6]),
                }

                layer_lengths = [float(tok) for tok in tokens[7:]]
                for i, length in enumerate(layer_lengths):
                    if length > 0:
                        active_layers.add(i)

                data[design][netName]["layer_lengths"] = layer_lengths
                data[design][netName]["routable_layer_lengths"] = [
                    length
                    for i, length in enumerate(layer_lengths)
                    # ignore non-routable layers
                    if stack[i][1]
                ]
                data[design][netName]["wire_length"] = sum(
                    length
                    for i, length in enumerate(layer_lengths)
                    # ignore non-routable layers
                    if stack[i][1]
                )
                data[design][netName]["grt_via_res"] = sum(
                    (length * stack[i][2])
                    for i, length in enumerate(layer_lengths)
                    if not stack[i][1]
                )

################################################################

if args.mode == "net" and args.plot_cap:
    # Compare the GRT cap estimate vs. OpenRCX SPEF cap

    diff_x = []
    diff_percent_x = []
    for design in data:
        for net in data[design]:
            grt_cap = data[design][net]["grt_cap"]
            rcx_cap = data[design][net]["rcx_cap"]
            diff = grt_cap - rcx_cap
            if abs(diff) > 1e-12:
                print("large discrapancy:", design, net, diff)
            if rcx_cap != 0.0:
                normDiff = (diff / rcx_cap) * 100
                diff_x.append(diff / cap_scale)
                diff_percent_x.append(normDiff)

    # Generate histograms
    num_bins = 200
    fig = plt.figure()
    fig.suptitle("Difference between GRT est. Cap and RCX Cap")
    plt.subplot(2, 2, 1)
    plt.hist(diff_x, num_bins, facecolor="blue", alpha=0.5)
    plt.ylabel("# Nets")
    plt.xlabel(
        "Capacitance ({})\n\nMean: {:.3f}{}\nStd. dev: {:.3f}fF".format(
            cap_unit, np.mean(diff_x), cap_unit, np.std(diff_x)
        )
    )

    plt.subplot(2, 2, 2)
    plt.hist(diff_percent_x, num_bins, range={-1000, 1000}, facecolor="blue", alpha=0.5)
    plt.ylabel("# Nets")
    plt.xlabel(
        "%\n\nMean: {:.3f}%\nStd. dev: {:.3f}%".format(
            np.mean(diff_percent_x), np.std(diff_percent_x)
        )
    )
    plt.show()

################################################################

if args.mode == "net" and args.plot_res:
    # Compare the GRT res estimate vs. OpenRCX SPEF res

    diff_x = []
    diff_percent_x = []
    for design in data:
        for net in data[design]:
            grt_res = data[design][net]["grt_res"]
            rcx_res = data[design][net]["rcx_res"]
            if grt_res > 0 and rcx_res > 0:
                diff = grt_res - rcx_res
                if abs(diff) > 1e3:
                    print("large discrapancy:", design, net, diff)
                if rcx_res != 0.0:
                    normDiff = (diff / rcx_res) * 100
                    diff_x.append(diff / res_scale)
                    diff_percent_x.append(normDiff)

    # Generate histograms
    num_bins = 200
    fig = plt.figure()
    fig.suptitle("Difference between GRT est. Res and RCX Res")
    plt.subplot(2, 2, 1)
    plt.hist(diff_x, num_bins, facecolor="blue", alpha=0.5)
    plt.ylabel("# Nets")
    plt.xlabel(
        "Resistance ({})\n\nMean: {:.3f}{}\nStd. dev: {:.3f}fF".format(
            res_unit, np.mean(diff_x), res_unit, np.std(diff_x)
        )
    )

    plt.subplot(2, 2, 2)
    plt.hist(diff_percent_x, num_bins, range={-1000, 1000}, facecolor="blue", alpha=0.5)
    plt.ylabel("# Nets")
    plt.xlabel(
        "%\n\nMean: {:.3f}%\nStd. dev: {:.3f}%".format(
            np.mean(diff_percent_x), np.std(diff_percent_x)
        )
    )
    plt.show()

################################################################

if args.mode == "net":
    # Use linear regression to find updated layer resistances.

    x = []
    y = []
    for design in data:
        for net in data[design]:
            rcx_res = data[design][net]["rcx_res"]
            if rcx_res > 0:
                x.append(data[design][net]["routable_layer_lengths"])
                y.append(rcx_res - data[design][net]["grt_via_res"])

    x = np.array(x)
    y = np.array(y)

    res_model = LinearRegression(fit_intercept=False).fit(x, y)
    r_sq = res_model.score(x, y)
    print("# Resistance coefficient of determination: {:.4f}".format(r_sq))

    ################################################################

    # Use linear regression to find updated layer capacitances.

    x = []
    y = []
    for design in data:
        for net in data[design]:
            x.append(data[design][net]["routable_layer_lengths"])
            y.append(data[design][net]["rcx_cap"])

    x = np.array(x)
    y = np.array(y)

    cap_model = LinearRegression(fit_intercept=False).fit(x, y)
    r_sq = cap_model.score(x, y)
    print("# Capacitance coefficient of determination: {:.4f}".format(r_sq))
    print(
        "# Updated layer resistance {}/um capacitance {}/um".format(res_unit, cap_unit)
    )

    routable_layers = [layer for layer in stack if layer[1]]
    for i, layer in enumerate(routable_layers):
        res_coeff = res_model.coef_[i]
        cap_coeff = cap_model.coef_[i]
        if res_coeff != 0.0 or cap_coeff != 0.0:
            print(
                "set_layer_rc -layer {} -resistance {:.5E} -capacitance {:.5E}".format(
                    layer[0], res_coeff / res_scale, cap_coeff / cap_scale
                )
            )

    ################################################################

    def generic_rc_fit(type_sieve):
        x = []
        y = []
        for design in data:
            for net in data[design]:
                net_type = data[design][net]["type"]
                wire_res = data[design][net]["rcx_res"]
                wire_length = data[design][net]["wire_length"]
                if net_type in type_sieve and wire_res != 0.0:
                    x.append([wire_length])
                    y.append(wire_res)
        x = np.array(x)
        y = np.array(y)
        wire_res_model = LinearRegression(fit_intercept=False).fit(x, y)
        wire_res = wire_res_model.coef_[0]

        x = []
        y = []
        for design in data:
            for net in data[design]:
                net_type = data[design][net]["type"]
                if net_type in type_sieve:
                    wire_length = data[design][net]["wire_length"]
                    wire_cap = data[design][net]["rcx_cap"]
                    x.append([wire_length])
                    y.append(wire_cap)
        x = np.array(x)
        y = np.array(y)
        wire_cap_model = LinearRegression(fit_intercept=False).fit(x, y)
        wire_cap = wire_cap_model.coef_[0]

        return "-resistance {:.5E} -capacitance {:.5E}".format(
            wire_res / res_scale, wire_cap / cap_scale
        )

    print("# Combined fit:")
    print("set_wire_rc " + generic_rc_fit(["signal", "clock"]))

    print("# Split signal/clock fit:")
    print("set_wire_rc -signal " + generic_rc_fit(["signal"]))
    print("set_wire_rc -clock " + generic_rc_fit(["clock"]))

################################################################

if args.mode == "segment":
    print("\nUnits: resistance [{}/um], capacitance [{}/um]".format(res_unit, cap_unit))

    # Note that the .csv data comes from ODB which stores capacitance in fF.
    cap_ff_to_f = 1e-15

    layer_models = {}
    for layer_name in routing_layers:
        # There may be routing layers with no segments, so we check if the
        # layer exists in the dict.
        if layer_name not in layer_segments:
            continue

        # sklearn requires the input to be 2D, so we reshape to add a dimension
        # to the list.
        lengths = np.array(layer_segments[layer_name]["lengths"]).reshape(-1, 1)
        resistances = np.array(layer_segments[layer_name]["resistances"])
        capacitances_ff = np.array(layer_segments[layer_name]["capacitances"])

        res_model = LinearRegression(fit_intercept=False).fit(lengths, resistances)
        cap_model = LinearRegression(fit_intercept=False).fit(lengths, capacitances_ff)
        layer_models[layer_name] = (
            res_model,
            cap_model,
            lengths,
            resistances,
            capacitances_ff,
        )

    # Print R² table
    print("{:<13s} | {:>8s} | {:>8s}".format("\nLayer", "Res R²", "Cap R²"))
    print("-" * 34)
    for layer_name, (
        res_model,
        cap_model,
        lengths,
        resistances,
        capacitances_ff,
    ) in layer_models.items():
        r_sq_res = compute_through_origin_fit_score(res_model, lengths, resistances)
        r_sq_cap = compute_through_origin_fit_score(cap_model, lengths, capacitances_ff)
        print("{:<12s} | {:>8s} | {:>8s}".format(layer_name, r_sq_res, r_sq_cap))
    print("-" * 34)
    print("")

    for layer_name, (
        res_model,
        cap_model,
        lengths,
        resistances,
        capacitances_ff,
    ) in layer_models.items():
        print(
            "set_layer_rc -layer {} -resistance {:.5E} -capacitance {:.5E}".format(
                layer_name,
                res_model.coef_[0] / res_scale,
                cap_model.coef_[0] * cap_ff_to_f / cap_scale,
            )
        )
    print("")

    def wire_rc_fit(target_net_type=None):
        total_length = 0.0
        total_resistance = 0.0
        total_capacitance = 0.0

        for layer_name, (res_model, cap_model, lengths, _, _) in layer_models.items():
            if target_net_type is not None:
                layer_length = sum(
                    layer_net_type_length[layer_name][net_type]
                    for net_type in target_net_type
                )
            else:
                layer_length = float(lengths.sum())

            total_resistance += res_model.coef_[0] * layer_length
            total_capacitance += cap_model.coef_[0] * layer_length
            total_length += layer_length

        if total_length == 0.0:
            return None

        return (
            total_resistance / total_length / res_scale,
            total_capacitance / total_length * cap_ff_to_f / cap_scale,
        )

    resistance, capacitance = wire_rc_fit()

    print(
        "set_wire_rc -resistance {:.5E} -capacitance {:.5E}".format(
            resistance, capacitance
        )
    )

    for net_type in ["signal", "clock"]:
        result = wire_rc_fit([net_type])

        if result is None:
            print("[Warning] No {} nets were found.".format(net_type))
            continue

        resistance, capacitance = result

        print(
            "set_wire_rc -{} -resistance {:.5E} -capacitance {:.5E}".format(
                net_type, resistance, capacitance
            )
        )
    print("")
