#!/usr/bin/env python3
"""Plot worst setup slack (WNS) per design, per PDK, from committed rules-base.json.

ORFS stores a golden-metrics baseline (rules-base.json) next to every design under
flow/designs/<pdk>/<design>/. Each baseline records the worst setup slack reached at
three flow stages:

    cts__timing__setup__ws
    globalroute__timing__setup__ws
    finish__timing__setup__ws

This script reads those values for every PDK that has them and regenerates, per PDK:

    flow/designs/<pdk>/wns.png      -- horizontal bar chart of finish-stage WNS
    flow/designs/<pdk>/README.md    -- a "## WNS" section (between generated markers)

No OpenROAD/ORFS flow run is required -- the data is already in the tree, so the plots
are deterministic and reproducible. Run from anywhere in the repo:

    python3 flow/util/plot_wns.py            # all PDKs
    python3 flow/util/plot_wns.py --pdk asap7  # one PDK

Only matplotlib (pinned in flow/util/requirements_lock.txt) and the standard library are
used.
"""

import argparse
import json
import os
import sys

import matplotlib

matplotlib.use("Agg")  # headless: write PNGs, never open a window
import matplotlib.pyplot as plt  # noqa: E402

# Stage key -> (short label, plot marker). Order is flow order.
STAGES = [
    ("cts__timing__setup__ws", "cts", "v"),
    ("globalroute__timing__setup__ws", "globalroute", "^"),
    ("finish__timing__setup__ws", "finish", None),  # finish is drawn as the bar
]
FINISH_KEY = "finish__timing__setup__ws"

BEGIN = "<!-- BEGIN WNS (generated by flow/util/plot_wns.py) -->"
END = "<!-- END WNS -->"


def designs_dir():
    """flow/designs, located relative to this script (flow/util/plot_wns.py)."""
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "designs"))


def load_value(path, key):
    """Return the float value for `key` in a rules-base.json, or None if absent."""
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, ValueError):
        return None
    entry = data.get(key)
    if isinstance(entry, dict) and isinstance(entry.get("value"), (int, float)):
        return float(entry["value"])
    return None


def collect(pdk_dir):
    """Return [(design, {stage_label: value_or_None}), ...] for designs with WNS data."""
    rows = []
    for design in sorted(os.listdir(pdk_dir)):
        rules = os.path.join(pdk_dir, design, "rules-base.json")
        if not os.path.isfile(rules):
            continue
        vals = {label: load_value(rules, key) for key, label, _ in STAGES}
        if vals["finish"] is None:  # need at least the headline metric
            continue
        rows.append((design, vals))
    # worst (most negative) finish slack first
    rows.sort(key=lambda r: r[1]["finish"])
    return rows


def plot_pdk(pdk, rows, out_png):
    names = [r[0] for r in rows]
    finish = [r[1]["finish"] for r in rows]
    y = list(range(len(names)))

    fig_h = max(2.5, 0.42 * len(names) + 1.2)
    fig, ax = plt.subplots(figsize=(9, fig_h))

    colors = ["#c0392b" if v < 0 else "#27ae60" for v in finish]
    ax.barh(y, finish, color=colors, height=0.6, zorder=2,
            label="finish (bar)")

    # overlay cts / globalroute as markers to show stage-to-stage movement
    for key, label, marker in STAGES:
        if marker is None:
            continue
        xs = [r[1][label] for r in rows]
        yy = [yi for yi, x in zip(y, xs) if x is not None]
        xx = [x for x in xs if x is not None]
        if xx:
            ax.scatter(xx, yy, marker=marker, s=40, zorder=3,
                       edgecolors="black", linewidths=0.4, label=label)

    ax.axvline(0, color="black", linewidth=0.8, zorder=1)
    ax.set_yticks(y)
    ax.set_yticklabels(names)
    ax.invert_yaxis()  # worst slack on top
    ax.set_xlabel("worst setup slack (PDK native timing unit; negative = not met)")
    ax.set_title(f"WNS by design — {pdk}")
    ax.grid(axis="x", linestyle=":", alpha=0.5, zorder=0)
    ax.legend(loc="lower right", fontsize=8, framealpha=0.9)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)


def fmt(v):
    return "" if v is None else f"{v:g}"


def wns_section(pdk, rows):
    lines = [
        BEGIN,
        "## WNS",
        "",
        "Worst setup slack per design at three flow stages — clock-tree synthesis "
        "(`cts`), global route (`globalroute`) and `finish` — read from each "
        "design's `rules-base.json`. Negative means setup timing is not met. Values are "
        "in this PDK's native timing unit (ps for `asap7`, ns for most others), so they "
        "are comparable within this PDK but not across PDKs.",
        "",
        "The bar is the `finish` slack; the markers show the `cts` and `globalroute` "
        "slack for the same design, so stage-to-stage movement is visible.",
        "",
        f"![WNS by design — {pdk}](wns.png)",
        "",
        "| design | cts | globalroute | finish |",
        "| --- | ---: | ---: | ---: |",
    ]
    for design, vals in rows:
        lines.append(
            f"| {design} | {fmt(vals['cts'])} | "
            f"{fmt(vals['globalroute'])} | {fmt(vals['finish'])} |"
        )
    lines += [
        "",
        "_Generated by `flow/util/plot_wns.py` from `rules-base.json`; regenerate with "
        "`python3 flow/util/plot_wns.py`._",
        END,
    ]
    return "\n".join(lines) + "\n"


def write_readme(readme_path, pdk, section):
    """Create README or replace the WNS section between markers, preserving prose."""
    if os.path.isfile(readme_path):
        with open(readme_path) as f:
            text = f.read()
        if BEGIN in text and END in text:
            pre = text[: text.index(BEGIN)]
            post = text[text.index(END) + len(END):]
            new = pre + section + post.lstrip("\n")
        else:
            new = text.rstrip("\n") + "\n\n" + section
    else:
        new = f"# {pdk} designs\n\n" + section
    with open(readme_path, "w") as f:
        f.write(new)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pdk", help="only process this PDK (default: all)")
    args = ap.parse_args()

    base = designs_dir()
    if not os.path.isdir(base):
        sys.exit(f"flow/designs not found at {base}")

    pdks = sorted(
        d for d in os.listdir(base)
        if os.path.isdir(os.path.join(base, d))
    )
    if args.pdk:
        pdks = [p for p in pdks if p == args.pdk]
        if not pdks:
            sys.exit(f"no such PDK directory: {args.pdk}")

    processed = 0
    for pdk in pdks:
        pdk_dir = os.path.join(base, pdk)
        rows = collect(pdk_dir)
        if not rows:
            continue
        plot_pdk(pdk, rows, os.path.join(pdk_dir, "wns.png"))
        write_readme(os.path.join(pdk_dir, "README.md"), pdk, wns_section(pdk, rows))
        miss = sum(1 for _, v in rows if v["finish"] < 0)
        print(f"{pdk}: {len(rows)} designs ({miss} with negative finish WNS)")
        processed += 1

    if not processed:
        sys.exit("no PDKs with rules-base.json WNS data found")
    print(f"done: {processed} PDK(s)")


if __name__ == "__main__":
    main()
