#!/usr/bin/env python3
"""Plot worst setup slack (WNS) per design, per PDK, from committed rules-base.json.

ORFS stores a golden-metrics baseline (rules-base.json) next to every design under
flow/designs/<pdk>/<design>/. Each baseline records the worst setup slack reached at
three flow stages:

    cts__timing__setup__ws
    globalroute__timing__setup__ws
    finish__timing__setup__ws

This script reads those values for every PDK that has them and regenerates, per PDK:

    flow/designs/<pdk>/wns.png      -- horizontal bar chart of finish-stage WNS
    flow/designs/<pdk>/README.md    -- a "## WNS" section (between generated markers)

It also produces a cross-PDK view of how well the cts/globalroute estimates predict the
final WNS (each design's per-stage estimate error, normalized by its clock period so the
PDKs are comparable):

    flow/designs/wns_accuracy.png   -- per-PDK strip plot of normalized estimate error
    flow/designs/README.md          -- a "## WNS estimate accuracy across PDKs" section

No OpenROAD/ORFS flow run is required -- the data is already in the tree, so the plots
are deterministic and reproducible. Run from anywhere in the repo:

    python3 flow/util/plot_wns.py            # all PDKs
    python3 flow/util/plot_wns.py --pdk asap7  # one PDK

Only matplotlib (pinned in flow/util/requirements_lock.txt) and the standard library are
used.
"""

import argparse
import glob
import json
import os
import re
import sys

import matplotlib

matplotlib.use("Agg")  # headless: write PNGs, never open a window
import matplotlib.pyplot as plt  # noqa: E402

# Stage key -> (short label, plot marker). Order is flow order.
STAGES = [
    ("cts__timing__setup__ws", "cts", "v"),
    ("globalroute__timing__setup__ws", "globalroute", "^"),
    ("finish__timing__setup__ws", "finish", None),  # finish is drawn as the bar
]
FINISH_KEY = "finish__timing__setup__ws"

BEGIN = "<!-- BEGIN WNS (generated by flow/util/plot_wns.py) -->"
END = "<!-- END WNS -->"

ACC_BEGIN = "<!-- BEGIN WNS-ACCURACY (generated by flow/util/plot_wns.py) -->"
ACC_END = "<!-- END WNS-ACCURACY -->"

# Estimate stages whose accuracy (vs finish) we report, in flow order.
EST_STAGES = ["cts", "globalroute"]
EST_MARKERS = {"cts": "v", "globalroute": "^"}

_PERIOD_RE = (
    re.compile(r"set\s+clk_period\s+([0-9.]+)"),
    re.compile(r"create_clock[^\n]*-period\s+([0-9.]+)"),
)


def clock_period(design_dir):
    """Clock period for a design, parsed from its .sdc, or None if not found.

    Handles the two idioms used across PDKs: `set clk_period <N>` and
    `create_clock ... -period <N>`. Returns the first match (designs here are
    single-clock); units are the PDK's native timing unit, same as the WNS values.
    """
    for sdc in sorted(glob.glob(os.path.join(design_dir, "*.sdc"))):
        try:
            text = open(sdc, errors="ignore").read()
        except OSError:
            continue
        for rx in _PERIOD_RE:
            m = rx.search(text)
            if m:
                return float(m.group(1))
    return None


def designs_dir():
    """flow/designs, located relative to this script (flow/util/plot_wns.py)."""
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "designs"))


def load_value(path, key):
    """Return the float value for `key` in a rules-base.json, or None if absent."""
    try:
        with open(path) as f:
            data = json.load(f)
    except (OSError, ValueError):
        return None
    entry = data.get(key)
    if isinstance(entry, dict) and isinstance(entry.get("value"), (int, float)):
        return float(entry["value"])
    return None


def collect(pdk_dir):
    """Return [(design, {stage_label: value_or_None}), ...] for designs with WNS data."""
    rows = []
    for design in sorted(os.listdir(pdk_dir)):
        rules = os.path.join(pdk_dir, design, "rules-base.json")
        if not os.path.isfile(rules):
            continue
        vals = {label: load_value(rules, key) for key, label, _ in STAGES}
        if vals["finish"] is None:  # need at least the headline metric
            continue
        rows.append((design, vals))
    # worst (most negative) finish slack first
    rows.sort(key=lambda r: r[1]["finish"])
    return rows


def plot_pdk(pdk, rows, out_png):
    names = [r[0] for r in rows]
    finish = [r[1]["finish"] for r in rows]
    y = list(range(len(names)))

    fig_h = max(2.5, 0.42 * len(names) + 1.2)
    fig, ax = plt.subplots(figsize=(9, fig_h))

    colors = ["#c0392b" if v < 0 else "#27ae60" for v in finish]
    ax.barh(y, finish, color=colors, height=0.6, zorder=2,
            label="finish (bar)")

    # overlay cts / globalroute as markers to show stage-to-stage movement
    for key, label, marker in STAGES:
        if marker is None:
            continue
        xs = [r[1][label] for r in rows]
        yy = [yi for yi, x in zip(y, xs) if x is not None]
        xx = [x for x in xs if x is not None]
        if xx:
            ax.scatter(xx, yy, marker=marker, s=40, zorder=3,
                       edgecolors="black", linewidths=0.4, label=label)

    ax.axvline(0, color="black", linewidth=0.8, zorder=1)
    ax.set_yticks(y)
    ax.set_yticklabels(names)
    ax.invert_yaxis()  # worst slack on top
    ax.set_xlabel("worst setup slack (PDK native timing unit; negative = not met)")
    ax.set_title(f"WNS by design — {pdk}")
    ax.grid(axis="x", linestyle=":", alpha=0.5, zorder=0)
    ax.legend(loc="lower right", fontsize=8, framealpha=0.9)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)


def fmt(v):
    return "" if v is None else f"{v:g}"


def wns_section(pdk, rows):
    lines = [
        BEGIN,
        "## WNS",
        "",
        "Worst setup slack per design at three flow stages — clock-tree synthesis "
        "(`cts`), global route (`globalroute`) and `finish` — read from each "
        "design's `rules-base.json`. Negative means setup timing is not met. Values are "
        "in this PDK's native timing unit (ps for `asap7`, ns for most others), so they "
        "are comparable within this PDK but not across PDKs.",
        "",
        "The bar is the `finish` slack; the markers show the `cts` and `globalroute` "
        "slack for the same design, so stage-to-stage movement is visible.",
        "",
        f"![WNS by design — {pdk}](wns.png)",
        "",
        "| design | cts | globalroute | finish |",
        "| --- | ---: | ---: | ---: |",
    ]
    for design, vals in rows:
        lines.append(
            f"| {design} | {fmt(vals['cts'])} | "
            f"{fmt(vals['globalroute'])} | {fmt(vals['finish'])} |"
        )
    lines += [
        "",
        "_Generated by `flow/util/plot_wns.py` from `rules-base.json`; regenerate with "
        "`python3 flow/util/plot_wns.py`._",
        END,
    ]
    return "\n".join(lines) + "\n"


def splice_readme(path, section, begin, end, title):
    """Create README, or replace the marked section in place (preserving prose)."""
    if os.path.isfile(path):
        with open(path) as f:
            text = f.read()
        if begin in text and end in text:
            pre = text[: text.index(begin)]
            post = text[text.index(end) + len(end):]
            new = pre + section + post.lstrip("\n")
        else:
            new = text.rstrip("\n") + "\n\n" + section
    else:
        new = (f"# {title}\n\n" if title else "") + section
    with open(path, "w") as f:
        f.write(new)


# --- cross-PDK estimate accuracy --------------------------------------------

def collect_accuracy(pdk_dir):
    """Per-design normalized estimate error vs finish, in % of the clock period.

    Returns [(design, {stage: err_pct}), ...] for designs that have a clock period and
    finish + estimate-stage WNS. err_pct = 100 * (stage_ws - finish_ws) / period;
    positive means the stage was *optimistic* (reported more slack than the final result).
    Normalizing by clock period makes the error comparable across PDKs with different units.
    """
    out = []
    for design in sorted(os.listdir(pdk_dir)):
        ddir = os.path.join(pdk_dir, design)
        rules = os.path.join(ddir, "rules-base.json")
        if not os.path.isfile(rules):
            continue
        period = clock_period(ddir)
        fin = load_value(rules, FINISH_KEY)
        if not period or fin is None:
            continue
        errs = {}
        for stage in EST_STAGES:
            v = load_value(rules, f"{stage}__timing__setup__ws")
            if v is not None:
                errs[stage] = 100.0 * (v - fin) / period
        if errs:
            out.append((design, errs))
    return out


def _stats(rows, stage):
    vals = [e[stage] for _, e in rows if stage in e]
    if not vals:
        return None
    mae = sum(abs(v) for v in vals) / len(vals)
    bias = sum(vals) / len(vals)
    return len(vals), mae, bias, max(vals, key=abs)


def plot_accuracy(acc, out_png):
    """Strip plot: per-PDK distribution of cts/globalroute estimate error vs finish."""
    pdks = sorted(acc)
    colors = {"cts": "#2980b9", "globalroute": "#e67e22"}
    off = {"cts": -0.18, "globalroute": 0.18}

    fig, ax = plt.subplots(figsize=(max(8, 1.3 * len(pdks) + 2), 5.5))
    for i, pdk in enumerate(pdks):
        rows = acc[pdk]
        for stage in EST_STAGES:
            pts = [e[stage] for _, e in rows if stage in e]
            k = len(pts)
            xs = [
                i + off[stage] + (0 if k < 2 else (j / (k - 1) - 0.5) * 0.26)
                for j in range(k)
            ]
            ax.scatter(xs, pts, s=28, color=colors[stage], alpha=0.75,
                       edgecolors="black", linewidths=0.3, zorder=3,
                       label=stage if i == 0 else None)
            if pts:  # mean tick
                m = sum(pts) / k
                ax.plot([i + off[stage] - 0.12, i + off[stage] + 0.12], [m, m],
                        color=colors[stage], linewidth=2.5, zorder=4)

    ax.axhline(0, color="black", linewidth=0.9, zorder=1)
    ax.set_xticks(range(len(pdks)))
    ax.set_xticklabels([f"{p}\n(n={len(acc[p])})" for p in pdks])
    ax.set_ylabel("estimate − final WNS  (% of clock period)\n+ optimistic / − pessimistic")
    ax.set_title("WNS estimate accuracy by stage, across PDKs")
    ax.grid(axis="y", linestyle=":", alpha=0.5, zorder=0)
    ax.legend(title="estimate stage", loc="upper left", fontsize=9)
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    plt.close(fig)


def accuracy_section(acc):
    lines = [
        ACC_BEGIN,
        "## WNS estimate accuracy across PDKs",
        "",
        "How closely the earlier-stage worst-slack estimates (`cts`, `globalroute`) match "
        "the final (`finish`) WNS, per design, normalized by that design's clock period so "
        "PDKs with different timing units are comparable. Error is "
        "`(stage − finish) / clock_period`; **positive = optimistic** (the stage reported "
        "more slack than the design actually closes with), negative = pessimistic. Clock "
        "period is parsed from each design's `.sdc`; designs whose period could not be "
        "parsed are omitted.",
        "",
        "![WNS estimate accuracy by stage, across PDKs](wns_accuracy.png)",
        "",
        "Mean absolute error (MAE) and mean signed error (bias), in % of clock period:",
        "",
        "| PDK | designs | cts MAE | cts bias | grt MAE | grt bias | worst (design) |",
        "| --- | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for pdk in sorted(acc):
        rows = acc[pdk]
        cs, gs = _stats(rows, "cts"), _stats(rows, "globalroute")
        # worst single |error| over both stages, for context
        worst = max(
            ((abs(e[s]), e[s], d, s) for d, e in rows for s in e),
            default=(0, 0, "-", ""),
        )
        c = f"{cs[1]:.1f}% | {cs[2]:+.1f}%" if cs else " | "
        g = f"{gs[1]:.1f}% | {gs[2]:+.1f}%" if gs else " | "
        lines.append(
            f"| {pdk} | {len(rows)} | {c} | {g} | "
            f"{worst[1]:+.1f}% ({worst[2]} {worst[3]}) |"
        )
    lines += [
        "",
        "_Generated by `flow/util/plot_wns.py`; regenerate with "
        "`python3 flow/util/plot_wns.py`._",
        ACC_END,
    ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pdk", help="only process this PDK (default: all)")
    args = ap.parse_args()

    base = designs_dir()
    if not os.path.isdir(base):
        sys.exit(f"flow/designs not found at {base}")

    pdks = sorted(
        d for d in os.listdir(base)
        if os.path.isdir(os.path.join(base, d))
    )
    if args.pdk:
        pdks = [p for p in pdks if p == args.pdk]
        if not pdks:
            sys.exit(f"no such PDK directory: {args.pdk}")

    processed = 0
    for pdk in pdks:
        pdk_dir = os.path.join(base, pdk)
        rows = collect(pdk_dir)
        if not rows:
            continue
        plot_pdk(pdk, rows, os.path.join(pdk_dir, "wns.png"))
        splice_readme(os.path.join(pdk_dir, "README.md"), wns_section(pdk, rows),
                      BEGIN, END, f"{pdk} designs")
        miss = sum(1 for _, v in rows if v["finish"] < 0)
        print(f"{pdk}: {len(rows)} designs ({miss} with negative finish WNS)")
        processed += 1

    if not processed:
        sys.exit("no PDKs with rules-base.json WNS data found")

    # Cross-PDK estimate-accuracy view (only meaningful over all PDKs).
    if not args.pdk:
        acc = {}
        for pdk in pdks:
            rows = collect_accuracy(os.path.join(base, pdk))
            if rows:
                acc[pdk] = rows
        if acc:
            plot_accuracy(acc, os.path.join(base, "wns_accuracy.png"))
            splice_readme(os.path.join(base, "README.md"), accuracy_section(acc),
                          ACC_BEGIN, ACC_END, "ORFS designs")
            total = sum(len(v) for v in acc.values())
            print(f"accuracy: {total} designs across {len(acc)} PDKs (clock period found)")

    print(f"done: {processed} PDK(s)")


if __name__ == "__main__":
    main()
