#!/usr/bin/env python3
"""Generate the synthetic designs for the RCX-vs-GRT parasitic-divergence study.

Writes, for every (PDK, fanout) pair:
  flow/designs/src/rcx-fanout/fanout_<N>.v        (PDK-independent RTL)
  flow/designs/<pdk>/rcx-fanout-<N>/config.mk
  flow/designs/<pdk>/rcx-fanout-<N>/constraint.sdc
  flow/designs/<pdk>/rcx-fanout-<N>/io.tcl

The RTL is a left-to-right macro: one launch flop (the "hub") drives a single
net that fans out to N capture flops; inputs are pinned to the WEST edge and
outputs to the EAST edge, so the fan-out net physically spans the die. As N
grows the net leaves the region where the global-route parasitic *estimate*
tracks the post-route RCX *extraction* -- which is what the study measures.

Run from the flow/ directory:  python3 docs/rcx/gen_study.py
"""

import os

# fanout=1 is the "no fan-out" single-sink baseline; the sweep runs well past
# the "sane RTL" region (see docs/rcx/README.md) so the divergence is visible.
FANOUTS = [1, 2, 4, 8, 16, 32, 64, 128]

# Per-PDK knobs. width0/wpf set the die width (and thus the west->east fan-out
# net length, the dominant lever on the GRT-vs-RCX gap); coarser/older nodes
# need physically longer wires for the wire RC to matter, so they get a larger
# width scale. inset is the die->core spacing (must clear the PDN ring). clk is
# a constant fast period per PDK (the study normalizes WNS by it).
PDKS = {
    "asap7":      {"clk_period": 250,  "die_h": 12.0, "inset": 1.0,
                   "width0": 150.0, "wpf": 2.0,  "has_rcx": True, "extra": {}},
    "sky130hd":   {"clk_period": 8000, "die_h": 140.0, "inset": 12.0, "pin_pitch": 1.5,
                   "width0": 500.0, "wpf": 6.0,  "has_rcx": True, "extra": {}},
    "ihp-sg13g2": {"clk_period": 6000, "die_h": 160.0, "inset": 26.0, "pin_pitch": 1.5,
                   "width0": 500.0, "wpf": 6.0,  "has_rcx": True, "extra": {}},
    # gt2n ships no OpenRCX deck: its `final` stage falls back to the global
    # route estimate, so there is no extraction sign-off to diverge from. We
    # still run it (estimate-only) and annotate that in the plots. gt2n designs
    # must set MAX_ROUTING_LAYER (the flow requires it).
    "gt2n":       {"clk_period": 600,  "die_h": 12.0, "inset": 2.0,
                   "width0": 150.0, "wpf": 2.0,  "has_rcx": False,
                   "extra": {"MAX_ROUTING_LAYER": "M5"}},
}

HERE = os.path.dirname(os.path.abspath(__file__))
FLOW = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC_DIR = os.path.join(FLOW, "designs", "src", "rcx-fanout")


def verilog(n):
    return f"""// Generated by docs/rcx/gen_study.py -- do not edit by hand.
//
// Left-to-right fan-out macro: a single launch flop ("hub") drives a net that
// fans out to {n} capture flop(s). Inputs are on the WEST edge, outputs on the
// EAST edge (see io.tcl), so the fan-out net spans the die. Each sink is XOR'd
// with its own perturb bit and bonded to a distinct output, so synthesis can
// neither merge nor delete sinks. The hub is dont_touch so the resizer cannot
// clone the driver and shorten the net (which would erase the effect we study).
module fanout_{n} (
    input  wire           clock,
    input  wire           reset,
    input  wire           din,
    input  wire [{n - 1}:0] perturb,
    output reg  [{n - 1}:0] dout
);
    (* dont_touch = "true" *) reg hub;
    always @(posedge clock) begin
        if (reset) hub <= 1'b0;
        else       hub <= din;
    end

    integer i;
    always @(posedge clock) begin
        if (reset) dout <= {{{n}{{1'b0}}}};
        else begin
            for (i = 0; i < {n}; i = i + 1)
                dout[i] <= hub ^ perturb[i];
        end
    end
endmodule
"""


def config_mk(pdk, n, info):
    # The GRT-vs-RCX WNS gap is driven by absolute wire length (RC ~ L^2), so
    # the die must be wide enough that the west->east fan-out net is genuinely
    # long; otherwise the gap is only a few ps and invisible. ~150um exposes a
    # ~50ps gap on asap7; it grows with fan-out as the net carries more sinks.
    # Loose placement density lets the capture flops spread toward the east edge
    # (their pinned outputs) instead of clumping next to the hub.
    width = max(info["width0"], 8.0 + info["wpf"] * n)
    # Height must give the west/east edges enough IO-pin slots: the input edge
    # carries n perturb pins + clock/din/reset, the output edge carries n dout
    # pins. ~0.15 um/pin keeps a comfortable margin over the placer's slot count.
    die_h = max(info["die_h"], round((n + 4) * info.get("pin_pitch", 0.15), 1))
    ins = info["inset"]
    extra = "".join(
        f"export {k:<24} = {v}\n" for k, v in info.get("extra", {}).items()
    )
    return f"""# Generated by docs/rcx/gen_study.py -- do not edit by hand.
export PLATFORM               = {pdk}
export DESIGN_NAME            = fanout_{n}
export DESIGN_NICKNAME        = rcx-fanout-{n}

export VERILOG_FILES          = $(DESIGN_HOME)/src/rcx-fanout/fanout_{n}.v
export SDC_FILE               = $(DESIGN_HOME)/{pdk}/rcx-fanout-{n}/constraint.sdc
export IO_CONSTRAINTS         = $(DESIGN_HOME)/{pdk}/rcx-fanout-{n}/io.tcl

export DIE_AREA               = 0 0 {width:.1f} {die_h:.1f}
export CORE_AREA              = {ins:.1f} {ins:.1f} {width - ins:.1f} {die_h - ins:.1f}
export PLACE_DENSITY          = 0.10
{extra}
# Tiny design: keep the run fast.
export SKIP_LAST_GASP         ?= 1
"""


def constraint_sdc(pdk, n, info):
    # Self-contained (most platforms ship no generic constraints.sdc to source):
    # a single clock plus set_max_delay optimization targets for the io legs.
    # Only the reg->fan-out-net->reg arc is the timing-closure metric the study
    # plots; set_max_delay (not set_input/output_delay) avoids hold-cell
    # insertion and any clock-insertion-latency assumptions.
    p = info["clk_period"]
    opt = p - p // 5
    return f"""# Generated by docs/rcx/gen_study.py -- do not edit by hand.
current_design fanout_{n}

set clk_period {p}
create_clock -name clock -period {p} -waveform [list 0 [expr {p} / 2]] [get_ports clock]

if {{[llength [get_ports -quiet reset]] == 1}} {{
  set_false_path -from [get_ports reset]
}}

set non_clk_inputs [all_inputs -no_clocks]
set_max_delay -ignore_clock_latency {opt} -from $non_clk_inputs -to [all_registers]
set_max_delay -ignore_clock_latency {opt} -from [all_registers] -to [all_outputs]
set_max_delay {opt} -from $non_clk_inputs -to [all_outputs]
group_path -name reg2reg -from [all_registers] -to [all_registers]
"""


def io_tcl():
    return """# Generated by docs/rcx/gen_study.py -- do not edit by hand.
# Inputs on the WEST (left) edge, outputs on the EAST (right) edge, so the
# fan-out net spans the die from west to east.
set_io_pin_constraint -direction INPUT  -region left:*
set_io_pin_constraint -direction OUTPUT -region right:*
"""


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print("wrote", os.path.relpath(path, FLOW))


def main():
    for n in FANOUTS:
        write(os.path.join(SRC_DIR, f"fanout_{n}.v"), verilog(n))
    for pdk, info in PDKS.items():
        for n in FANOUTS:
            d = os.path.join(FLOW, "designs", pdk, f"rcx-fanout-{n}")
            write(os.path.join(d, "config.mk"), config_mk(pdk, n, info))
            write(os.path.join(d, "constraint.sdc"), constraint_sdc(pdk, n, info))
            write(os.path.join(d, "io.tcl"), io_tcl())


if __name__ == "__main__":
    main()
