# Platform configuration generated by config.py
# Same pattern as defaults.py in variables.mk:44
$(foreach line,$(shell $(PYTHON_EXE) $(PLATFORM_DIR)/config.py),$(eval export $(subst __SPACE__, ,$(line))))
