filegroup(
    name = "IPs",
    srcs = glob(["*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "verilog",
    srcs = glob(["*.v", "*.sv"], allow_empty = True),
    visibility = ["//visibility:public"],
)
