filegroup(
    name = "include",
    srcs = glob(["*.v", "*.sv", "*.svh"], allow_empty = True) + [
        "//flow/designs/src/mempool_group/rtl/register_interface/include/register_interface:assign.svh",
        "//flow/designs/src/mempool_group/rtl/register_interface/include/register_interface:typedef.svh",
    ],
    visibility = ["//visibility:public"],
)
