# Generated by docs/rcx/gen_study.py -- do not edit by hand.
export PLATFORM               = gt2n
export DESIGN_NAME            = fanout_128
export DESIGN_NICKNAME        = rcx-fanout-128

export VERILOG_FILES          = $(DESIGN_HOME)/src/rcx-fanout/fanout_128.v
export SDC_FILE               = $(DESIGN_HOME)/gt2n/rcx-fanout-128/constraint.sdc
export IO_CONSTRAINTS         = $(DESIGN_HOME)/gt2n/rcx-fanout-128/io.tcl

export DIE_AREA               = 0 0 264.0 19.8
export CORE_AREA              = 2.0 2.0 262.0 17.8
export PLACE_DENSITY          = 0.10
export MAX_ROUTING_LAYER        = M5

# Tiny design: keep the run fast.
export SKIP_LAST_GASP         ?= 1
