# Generated by docs/rcx/gen_study.py -- do not edit by hand.
current_design fanout_128

set clk_period 600
create_clock -name clock -period 600 -waveform [list 0 [expr 600 / 2]] [get_ports clock]

if {[llength [get_ports -quiet reset]] == 1} {
  set_false_path -from [get_ports reset]
}

set non_clk_inputs [all_inputs -no_clocks]
set_max_delay -ignore_clock_latency 480 -from $non_clk_inputs -to [all_registers]
set_max_delay -ignore_clock_latency 480 -from [all_registers] -to [all_outputs]
set_max_delay 480 -from $non_clk_inputs -to [all_outputs]
group_path -name reg2reg -from [all_registers] -to [all_registers]
