# Generated by docs/rcx/gen_study.py -- do not edit by hand.
# Inputs on the WEST (left) edge, outputs on the EAST (right) edge, so the
# fan-out net spans the die from west to east.
set_io_pin_constraint -direction INPUT  -region left:*
set_io_pin_constraint -direction OUTPUT -region right:*
