filegroup(
    name = "include",
    srcs = glob(["*.v", "*.sv", "*.svh"], allow_empty = True),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "verilog",
    srcs = glob(["*.v", "*.sv"], allow_empty = True),
    visibility = ["//visibility:public"],
)
