# Generated by docs/rcx/gen_study.py -- do not edit by hand.
export PLATFORM               = asap7
export DESIGN_NAME            = fanout_1
export DESIGN_NICKNAME        = rcx-fanout-1

export VERILOG_FILES          = $(DESIGN_HOME)/src/rcx-fanout/fanout_1.v
export SDC_FILE               = $(DESIGN_HOME)/asap7/rcx-fanout-1/constraint.sdc
export IO_CONSTRAINTS         = $(DESIGN_HOME)/asap7/rcx-fanout-1/io.tcl

export DIE_AREA               = 0 0 150.0 12.0
export CORE_AREA              = 1.0 1.0 149.0 11.0
export PLACE_DENSITY          = 0.10

# Tiny design: keep the run fast.
export SKIP_LAST_GASP         ?= 1
