#!/bin/bash
set -ex
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export ORFS=~/OpenROAD-flow-scripts
export FLOW_HOME=$ORFS/flow
export MAKEFILES=$FLOW_HOME/Makefile

cd $ORFS
. env.sh

cd $DIR
eval "$@"
