# Generated by docs/rcx/gen_study.py -- do not edit by hand.
export PLATFORM               = gt2n
export DESIGN_NAME            = fanout_64
export DESIGN_NICKNAME        = rcx-fanout-64

export VERILOG_FILES          = $(DESIGN_HOME)/src/rcx-fanout/fanout_64.v
export SDC_FILE               = $(DESIGN_HOME)/gt2n/rcx-fanout-64/constraint.sdc
export IO_CONSTRAINTS         = $(DESIGN_HOME)/gt2n/rcx-fanout-64/io.tcl

export DIE_AREA               = 0 0 150.0 12.0
export CORE_AREA              = 2.0 2.0 148.0 10.0
export PLACE_DENSITY          = 0.10
export MAX_ROUTING_LAYER        = M5

# Tiny design: keep the run fast.
export SKIP_LAST_GASP         ?= 1
