name: Lint Python

on: [push, pull_request]
jobs:
  lint:
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: psf/black@87928e6d6761a4a6d22250e1fee5601b3998086e  # 26.5.1
